### ISSUE TITLE
Feature Request: Turbo 8psk

### ISSUE THREAD

**Issue by andyss2k** [stefvie2k/dsrip#1]
Any chance you can code in turbo 8psk fec (2/3) used by 119W/110W/91W/82W/etc?  I get "Invalid FEC for Turbo!" when trying to tune in those sats.

**Comment by stefvie2k** [comment]
Try passing the following values for the given x/y FEC values:

8SPK Turbo FEC Rates: 2/3 (1.92), 3/4 (2.05), 3/4 (2.11), 3/4 (2.19),. 5/6 (2.30), 8/9 (2.40).

**Comment by andyss2k** [comment]
I get the following from the docker container (Unicast method):

~192.168.1.102 - - [12/Feb/2021 15:15:26] "GET /stream/?fe=1&pol=v&freq=974&modulation=turbo&sr=21500&fec=1.92 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/dsrip/dsrip.py", line 545, in do_GET
    tune(instance, session, qs)
  File "/opt/dsrip/dsrip.py", line 322, in tune
    fec = int(qs['fec'][0])
ValueError: invalid literal for int() with base 10: '1.92'

**Comment by stefvie2k** [comment]
Grab the latest and give that a try.

**Comment by andyss2k** [comment]
Sometimes I can lock, most times I can't. I can lock on the transponder when using DSRC, then when trying to tune in via DSRIP it now gives this with your latest:

192.168.1.102 - - [12/Feb/2021 16:14:44] "GET /stream/?fe=1&pol=v&freq=974&modulation=turbo&sr=21500&fec=1.92 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

Thanks for trying to work it out.  I really appreciate it.

**Comment by andyss2k** [comment]
More info to troubleshoot.  DSRC and DSRIP:

![Capture](https://user-images.githubusercontent.com/78926670/107795500-b6eb7080-6d26-11eb-8af5-2bd839943aa9.JPG)

And when locked via DSRC:

![Capture](https://user-images.githubusercontent.com/78926670/107796617-1302c480-6d28-11eb-8358-4b25d4f1e084.JPG)

**Comment by stefvie2k** [comment]
Grab latest and try again?

**Comment by andyss2k** [comment]
I'm still getting the errors about a broken pipe (above) but all transponders are locking in!  Thanks for fixing this, works great!

**Comment by stefvie2k** [comment]
What sort of streaming is your DSR configured as? Unicast or Multicast?

BTW, is CTV Moncton opened on 82W? That's one of the station I used to watch growing up in Bathurst. :)

**Comment by andyss2k** [comment]
Ha, no they are not open.  I'm just playing around with the different sats (from here in Toronto) just to get familiar with the DSR.  I'm set up for unicast.

**Comment by stefvie2k** [comment]
I just did a test using Unicast. Make sure that the IP address configured on the DSR-6000 is that of your docker host. I have my TS port to 1000 so this is the command that I then ran:

vm-dev:~/dsrip$ sudo docker run -i --network host -p 6100:6100/udp -p 8600:8600 -e DSRIP_LISTEN_PORT=8600 -e DSRIP_SNMP_ADDRESS=192.168.1.100 -e DSRIP_STREAM_URL=udp://@:1000 -e DSRIP_LOF=5150 -e DSRIP_HPORT=0 -e DSRIP_VPORT=1 -t dsrip /opt/dsrip/start.sh

**Comment by andyss2k** [comment]
Yup, that's how I have it set up.  Maybe my DSR is a bit finicky, lol.  Anyways, thanks again for helping me out.  I will let you know if there are any more major hiccups.

**Comment by stefvie2k** [comment]
I've been playing with it for the pass hour or so on 91W and all seems to be working fine. It tune+streams properly.

**Comment by andyss2k** [comment]
Yeah, it locks in perfectly now.
